version: '3.8'
services:
  backend:
    build:
      context: .
      target: development
    container_name: 'backend'
    ports:
      - '8080:8080'
    depends_on:
      - database
  database:
    image: 'postgres:13.6-alpine3.15'
    container_name: 'database'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=todo-app'
    volumes:
      - pg_data:/var/lib/pg
volumes:
  pg_data:
